### ISSUE TITLE
compilation issue under bitbake

### ISSUE THREAD

**Issue by dl9pf** [amanarora9848/voicerecognizer-gst-grpc#6]
| [        ] MSG : Logs written to /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/pub_cache/log/pub_log.txt.
| [  +21 ms] Running "flutter pub get" in app... (completed in 391ms)
| [  +62 ms] 💪 Building with sound null safety 💪
| [   +3 ms] Initializing file store
| [   +7 ms] Skipping target: gen_localizations
| [   +7 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents: /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/git/app/.dart_tool/package_config_subset}
| [  +16 ms] gen_dart_plugin_registrant: Complete
| [        ] kernel_snapshot: Starting due to {}
| [   +6 ms] /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin/cache/dart-sdk/bin/dart --disable-dart-dev /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/recipe-sysroot-native/usr/share/flutter/sdk/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/git/app/.dart_tool/package_config.json --output-dill /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/git/app/.dart_tool/flutter_build/afe03443a71830c16c6127abbf23fc55/app.dill --depfile /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/git/app/.dart_tool/flutter_build/afe03443a71830c16c6127abbf23fc55/kernel_snapshot.d --filesystem-scheme org-dartlang-root --incremental --initialize-from-dill /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/git/app/.dart_tool/flutter_build/afe03443a71830c16c6127abbf23fc55/app.dill --verbosity=error package:flutter_vosk_demo/main.dart
| [ +177 ms] Error: Couldn't resolve the package 'app' in 'package:app/src/generated/recognize.pbgrpc.dart'.
| [   +5 ms] lib/main.dart:4:8: Error: Not found: 'package:app/src/generated/recognize.pbgrpc.dart'
| [        ] import 'package:app/src/generated/recognize.pbgrpc.dart';
| [        ]        ^
| [+2070 ms] lib/main.dart:16:12: Error: The method 'RecognizerServiceClient' isn't defined for the class 'RecognizeVoice'.
| [        ]  - 'RecognizeVoice' is from 'package:flutter_vosk_demo/main.dart' ('lib/main.dart').
| [        ] Try correcting the name to the name of an existing method, or defining a method named 'RecognizerServiceClient'.
| [        ]     stub = RecognizerServiceClient(channel);
| [        ]            ^^^^^^^^^^^^^^^^^^^^^^^
| [        ] lib/main.dart:20:26: Error: The method 'RecognizerControl' isn't defined for the class 'RecognizeVoice'.
| [        ]  - 'RecognizeVoice' is from 'package:flutter_vosk_demo/main.dart' ('lib/main.dart').
| [        ] Try correcting the name to the name of an existing method, or defining a method named 'RecognizerControl'.
| [        ]     await stub.recognize(RecognizerControl()..action = RecognizerAction.START);
| [        ]                          ^^^^^^^^^^^^^^^^^
| [   +2 ms] lib/main.dart:20:56: Error: The getter 'RecognizerAction' isn't defined for the class 'RecognizeVoice'.
| [        ]  - 'RecognizeVoice' is from 'package:flutter_vosk_demo/main.dart' ('lib/main.dart').
| [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'RecognizerAction'.
| [        ]     await stub.recognize(RecognizerControl()..action = RecognizerAction.START);
| [        ]                                                        ^^^^^^^^^^^^^^^^
| [   +1 ms] lib/main.dart:25:20: Error: The method 'RecognizerControl' isn't defined for the class 'RecognizeVoice'.
| [        ]  - 'RecognizeVoice' is from 'package:flutter_vosk_demo/main.dart' ('lib/main.dart').
| [        ] Try correcting the name to the name of an existing method, or defining a method named 'RecognizerControl'.
| [        ]         .recognize(RecognizerControl()..action = RecognizerAction.STOP);
| [        ]                    ^^^^^^^^^^^^^^^^^
| [        ] lib/main.dart:25:50: Error: The getter 'RecognizerAction' isn't defined for the class 'RecognizeVoice'.
| [        ]  - 'RecognizeVoice' is from 'package:flutter_vosk_demo/main.dart' ('lib/main.dart').
| [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'RecognizerAction'.
| [        ]         .recognize(RecognizerControl()..action = RecognizerAction.STOP);
| [        ]                                                  ^^^^^^^^^^^^^^^^
| [+4161 ms] Unhandled exception:
|            FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aapp%2Fsrc%2Fgenerated%2Frecognize.pbgrpc.dart; message=StandardFileSystem only supports file:* and data:* URIs)
|            #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
|            #1      asFileUri (package:vm/kernel_front_end.dart:659:37)
|            #2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
|            <asynchronous suspension>
|            #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
|            <asynchronous suspension>
|            #4      starter (package:frontend_server/frontend_server.dart:1451:12)
|            <asynchronous suspension>
|            #5      main (file:///b/s/w/ir/cache/builder/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
|            <asynchronous suspension>
|
| [ +192 ms] Persisting file store
| [   +2 ms] Done persisting file store
| [   +1 ms] Target kernel_snapshot failed: Exception
| [        ] "flutter bundle" took 12,469ms.
| [   +2 ms] Failed to build bundle.
| [        ]
|            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
|            #1      BundleBuilder.build (package:flutter_tools/src/bundle_builder.dart:84:7)
|            <asynchronous suspension>
|            #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:137:5)
|            <asynchronous suspension>
|            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
|            <asynchronous suspension>
|            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
|            <asynchronous suspension>
|            #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
|            <asynchronous suspension>
|            #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
|            <asynchronous suspension>
|            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
|            <asynchronous suspension>
|            #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
|            <asynchronous suspension>
|            #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
|            <asynchronous suspension>
|            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
|            <asynchronous suspension>
|            #11     main (package:flutter_tools/executable.dart:91:3)
|            <asynchronous suspension>
|
|
| [        ] Running shutdown hooks
| [        ] Shutdown hooks complete
| [        ] exiting with code 1
| WARNING: /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/temp/run.do_compile.112344:154 exit 1 from 'flutter build bundle -v'
| WARNING: Backtrace (BB generated script):
|       #1: do_compile, /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/temp/run.do_compile.112344, line 154
|       #2: main, /home/dl9pf/yocto/build-app-pi4/tmp/work/aarch64-agl-linux/flutter-vosk-demo/git-r0/temp/run.do_compile.112344, line 220
ERROR: Task (/home/dl9pf/AGL/master/meta-agl-devel/meta-offline-voice-agent/dynamic-layers/meta-agl-demo/recipes-demo/flutter-vosk-demo/flutter-vosk-demo_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2663 tasks of which 2447 didn't need to be rerun and 1 failed.
NOTE: Build completion summary:
NOTE:   do_populate_sysroot: 100.0% sstate reuse(205 setscene, 0 scratch)
NOTE:   do_deploy_source_date_epoch: 100.0% sstate reuse(1 setscene, 0 scratch)
NOTE:   do_package_qa: 100.0% sstate reuse(87 setscene, 0 scratch)
NOTE:   do_packagedata: 100.0% sstate reuse(88 setscene, 0 scratch)
NOTE:   do_package_write_rpm: 100.0% sstate reuse(87 setscene, 0 scratch)
NOTE:   do_populate_lic: 100.0% sstate reuse(206 setscene, 0 scratch)
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 5 seconds

Summary: 1 task failed:
  /home/dl9pf/AGL/master/meta-agl-devel/meta-offline-voice-agent/dynamic-layers/meta-agl-demo/recipes-demo/flutter-vosk-demo/flutter-vosk-demo_git.bb:do_compile

**Comment by dl9pf** [comment]
| [ +5 ms] lib/main.dart:4:8: Error: Not found: 'package:app/src/generated/recognize.pbgrpc.dart'

**Comment by amanarora9848** [comment]
The dart proto files are kept in app/lib/src/generated (https://github.com/amanarora9848/voicerecognizer-gst-grpc/tree/master/app/lib/src/generated). I am not sure why there is no lib/ as the error says

**Comment by amanarora9848** [comment]
Issue fixed thanks to patch(es) from @dl9pf
